@echo off
echo 🚀 Démarrage du backend FastAPI...
cd /d "%~dp0backend"
echo 📦 Installation des dépendances...
pip install -r ..\requirements.txt
echo 🔥 Lancement du serveur...
python main.py
pause